config/routes.rb
Rails.application.routes.draw do
  
  get 'news_pages/newsPage1'

  get 'news_pages/newsPage2'

  get 'news_pages/newsPage3'

  get 'news_pages/newsPage4'

  get 'sessions/new'
  
  get 'contact', to: 'messages#contact'

  get 'message/new'

  get 'contact/new'

  get 'staff_logins/new'

  root 'static_pages#home' 
  
  get '/home', to: 'static_pages#home'

  get '/treatments', to: 'static_pages#treatments'

  get '/news', to: 'static_pages#news'

  get 'static_pages/contactUs'

  get '/aboutUs', to: 'static_pages#aboutUs'

  get '/login', to: 'staff_logins#new'
  
  post '/login',   to: 'staff_logins#create'
  
  delete '/logout',  to: 'staff_logins#destroy'
  
  get  '/signup',  to: 'staff_creations#new'
  
  post  '/signup',  to: 'staff_creations#create'


  get 'static_pages/admin'

  get 'static_pages/staff'
  
  post '/contact', to: 'messages#create'
  
  get '/contact', to: 'messages#new'
  
  post '/staff_logins/2', to: 'newspages#create'
  post '/staff_logins/2', to: 'newspages#destroy'
  post '/newsOne', to: 'newspages#create'
  
  post '/staff_logins/2', to: 'newstwopage#create'
  post '/staff_logins/2', to: 'newstwopage#destroy'
  post '/newsTwo', to: 'newstwopage#create'
  
  post '/staff_logins/2', to: 'newsthreepage#create'
  post '/staff_logins/2', to: 'newsthreepage#destroy'
  post '/newsThree', to: 'newsthreepage#create'
  
  post '/staff_logins/2', to: 'newsfourpage#create'
  post '/staff_logins/2', to: 'newsfourpage#destroy'
  post '/newsFour', to: 'newsfourpage#create'
  
  resources :staff_logins

  resources :messages
  
  resources :newspages
  
  resources :newstwopage
  resources :newsthreepage
  resources :newsfourpage


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/dentist.rb
class Dentist < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    
end

app/models/news_two_page.rb
class NewsTwoPage < ApplicationRecord
end

app/models/newsfourpage.rb
class Newsfourpage < ApplicationRecord
end

app/models/newspage.rb
class Newspage < ApplicationRecord
end

app/models/newsthreepage.rb
class Newsthreepage < ApplicationRecord
end

app/models/newstwopage.rb
class Newstwopage < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/models/staff_creation.rb
class StaffCreation < ApplicationRecord
    validates :staffId, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :address, presence: true, length: { maximum: 255 }
    before_save{ self.email = staffId.downcase }
    before_save { self.staffId = staffId.downcase }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/staff_login.rb
class StaffLogin < ApplicationRecord
    validates :staffId, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :address, presence: true, length: { maximum: 255 }
    before_save{ self.email = staffId.downcase }
    before_save { self.staffId = staffId.downcase }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def contact
  end
  
  def new
    @message = Message.new
    if @message.save
      flash[:success] = "Thanks for contacting us!"
      redirect_to home_url
    else
      render 'contact'
    end
  end
  
  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:success] = "Thanks for contacting us!"
      redirect_to home_url
    else
      render 'contact'
       flash[:success] = "failed!"
    end
  end
  
  def show
    @message = Message.first
  end
  
  
  def message_params
      params.require(:message).permit(:messageName, :messageEmail, :messageTitle, :messageText, :messagePhone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_pages_helper.rb
module NewsPagesHelper
end

app/helpers/newspage_helper.rb
module NewspageHelper
end

app/helpers/newspagetwo_helper.rb
module NewspagetwoHelper
end

app/helpers/newstwopage_helper.rb
module NewstwopageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/twopage_helper.rb
module TwopageHelper
end

app/views/messages/contact.html.erb
<%=yield %>


<% provide(:title, "contact us") %>

<%=yield %>


<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= yield(:title) %> | Ruby on Rails Group Project</title>
</head>

<body>
  <h2 style="text-align:center; margin-bottom:30px;"> CONTACT US</h2>
  <!-- main container start -->
<div class="container">
  <!-- top row start  -->
  <div class="row">
    <div class="col-xs-12 col-md-4 col-lg-4" style="text-align:center; padding-top: 30px;"> 
        <%= image_tag("phone.png") %>
        <br>
        <h2>Our Phone</h2>
        <p>Call: <a "text-align: center; font-size: 14px;" href="tel:01-439 6815">01-282 1111 </a>
            <br> Monday-Friday
            <br> 8am-6pm </p>
    </div>
      <!-- form start -->
    <div class="col-xs-12 col-md-4 col-lg-4 well">
      
        
        
        <!--<% provide(:title, 'Sign up') %>-->
        <h2 class="bookAppointment">Book an appointment</h2>

          <%= form_for(:message, url: contact_url) do |f| %>
         
    
            <%= f.label :name %>
            <%= f.text_field :messageName %>
          
            <%= f.label :email %>
            <%= f.email_field :messageEmail %>
          
            <%= f.label :phone %>
            <%= f.text_field :messagePhone %>
          
            <%= f.label :title %>
            <%= f.text_field :messageTitle %>
          
            <%= f.label :message %>
            <%= f.text_field :messageText %>
          
            <%= f.submit "Send Message", class: "btn btn-primary", id:"top"%>
          <% end %>
    </div>
    <!-- form end  -->
    <div class="col-xs-12 col-md-4 col-lg-4" style="text-align: center; padding-top: 30px;">
        <a href="mailto:test@gmail.com">
        <%= image_tag("email.png") %>
          </a>
        <br>
        <h2>Email</h2>
        <p>Send an email to:
            <br> <a href="mailto:test@gmail.com" target="_top">test@gmail.com.ie </a> </p>
    </div>
  </div>
<!-- top end  -->  
<!-- Add Google Maps start -->
  <div class="row">
    <div class="large-12 small-12 columns">
      <h2 style="text-align:center;"> Our Location</h2>
      <iframe style="width:100%; height:400px;border-radius:20px;" class="float-center" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDA1_kypL3-F88HK7I3vMNp5ve-B_0Mom0 &q=Griffith College, S Circular Rd, Merchants Quay, Dublin 8, Ireland" allowfullscreen> </iframe> 
    </div>
  </div>  
    <!-- Add Google Maps end -->

</div>
<!-- main container end -->

</body>
</html>