config/routes.rb
Rails.application.routes.draw do
  
  get 'news_pages/newsPage1'

  get 'news_pages/newsPage2'

  get 'news_pages/newsPage3'

  get 'news_pages/newsPage4'

  get 'sessions/new'
  
  get 'contact', to: 'messages#contact'

  get 'message/new'

  get 'contact/new'

  get 'staff_logins/new'

  root 'static_pages#home' 
  
  get '/home', to: 'static_pages#home'

  get '/treatments', to: 'static_pages#treatments'

  get '/news', to: 'static_pages#news'

  get 'static_pages/contactUs'

  get '/aboutUs', to: 'static_pages#aboutUs'

  get '/login', to: 'staff_logins#new'
  
  post '/login',   to: 'staff_logins#create'
  
  delete '/logout',  to: 'staff_logins#destroy'
  
  get  '/signup',  to: 'staff_creations#new'
  
  post  '/signup',  to: 'staff_creations#create'


  get 'static_pages/admin'

  get 'static_pages/staff'
  
  post '/contact', to: 'messages#create'
  
  get '/contact', to: 'messages#new'
  
  post '/staff_logins/2', to: 'newspages#create'
  post '/staff_logins/2', to: 'newspages#destroy'
  post '/newsOne', to: 'newspages#create'
  
  post '/staff_logins/2', to: 'newstwopage#create'
  post '/staff_logins/2', to: 'newstwopage#destroy'
  post '/newsTwo', to: 'newstwopage#create'
  
  post '/staff_logins/2', to: 'newsthreepage#create'
  post '/staff_logins/2', to: 'newsthreepage#destroy'
  post '/newsThree', to: 'newsthreepage#create'
  
  post '/staff_logins/2', to: 'newsfourpage#create'
  post '/staff_logins/2', to: 'newsfourpage#destroy'
  post '/newsFour', to: 'newsfourpage#create'
  
  resources :staff_logins

  resources :messages
  
  resources :newspages
  
  resources :newstwopage
  resources :newsthreepage
  resources :newsfourpage


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/dentist.rb
class Dentist < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    
end

app/models/news_two_page.rb
class NewsTwoPage < ApplicationRecord
end

app/models/newsfourpage.rb
class Newsfourpage < ApplicationRecord
end

app/models/newspage.rb
class Newspage < ApplicationRecord
end

app/models/newsthreepage.rb
class Newsthreepage < ApplicationRecord
end

app/models/newstwopage.rb
class Newstwopage < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/models/staff_creation.rb
class StaffCreation < ApplicationRecord
    validates :staffId, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :address, presence: true, length: { maximum: 255 }
    before_save{ self.email = staffId.downcase }
    before_save { self.staffId = staffId.downcase }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/staff_login.rb
class StaffLogin < ApplicationRecord
    validates :staffId, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :address, presence: true, length: { maximum: 255 }
    before_save{ self.email = staffId.downcase }
    before_save { self.staffId = staffId.downcase }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_pages_helper.rb
module NewsPagesHelper
end

app/helpers/newspage_helper.rb
module NewspageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/twopage_helper.rb
module TwopageHelper
end

app/views/layouts/_addStaffForm.html.erb
<h4>Add a New Staff Member</h4>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:staff_creation, url: signup_path) do |f| %>

      <%= f.label :staffId %>
      <%= f.text_field :staffId, class: 'form-control' , :required => true%><br>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' , :required => true%><br>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' , :required => true%><br>
      
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' , :required => true%><br>
      
      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: 'form-control' , :required => true %><br>

      <%= f.label :role %><br>
      <%= f.select :role, [['Manager','manager'],['Staff','staff']], class: 'form-control' , :required => true%><br><br>
      
      <%= f.label :accessLevel %><br>
      <%= f.select :accessLevel, [['Admin','admin'],['Staff','staff']], class: 'form-control' , :required => true %><br><br>
      
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "min 6 characters", class: 'form-control', :required => true, :minLength => 6  %>

      <%= f.submit "Create New Staff Member", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="container-fluid" style="background-color: red; margin-top: 20px;">
    <div class="row">
        <div class="col-md-9">
            <p class="foot">Goup Assignment - Paul O'Sullivan - 2887084, Barrie Kealy - 2965845, Stephen Cagney - 2887147</p>
        </div>
        <div class="col-md-3" >
          <ul class="nav navbar-nav">
            <!--<li><a style="color:#ffffff;" href="/staff_logins/new">Staff Login</a></li>-->
            <li><a style="color:#ffffff;" href="/contact.html">Contact us</a></li>
            <li><a style="color:#ffffff;" href="/aboutUs.html">About us</a></li>

          </ul>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<!-- navigation start -->
<nav class="navbar navbar-default navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "HOME",   '/home.html' %></li>
        <li><%= link_to "TREATMENTS",   '/treatments.html' %></li>
        <li><%= link_to "NEWS",   '/news.html' %></li>
        <li><%= link_to "CONTACT US",   '/contact.html' %></li>
        <li><%= link_to "ABOUT US",   '/aboutUs.html' %></li>
                      <% if logged_in? %>
            <li><%= link_to "StaffLogin", '#' %></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
                </a>
              <ul class="dropdown-menu" style="background-color:#f4511e">
                <li><%= link_to "Profile", current_staff %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
      </ul>
    </div>
  </div>
</nav>
<!-- navigation End -->

app/views/layouts/_managerForm.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h4> Hello <%= @staff_login.name %>,</h1>
      
     <a href= "../news_pages/newsPage1" > <button type button class= "btn btn-primary"> News item 1  </button> </a>
     <a href= "../news_pages/newsPage2" > <button type button class= "btn btn-danger"> News item 2   </button> </a>
     <a href= "../news_pages/newsPage3" > <button type button class= "btn btn-success"> News item 3  </button> </a>
     <a href= "../news_pages/newsPage4" > <button type button class= "btn btn-info"> News item 4     </button> </a>
     
  </div>
</div>

app/views/layouts/_receptionForm.html.erb
<div class="row">
  <div class:"appointment">
    <h4>Hello <%= @staff_login.name %>, here is the messages from customers</h1>
  
     <!-- form start -->
      <div class="col-xs-12 col-md-4 col-lg-4 well">
       
         <% Message.all.each do |message| %>
            ID: <%= message.id %> </br>
            Name: <%= message.messageName %> </br>
            Email: <%= message.messageEmail %> </br>
            Phone number: <%= message.messagePhone %> </br>
            Title: <%= message.messageTitle %> </br>
            Time: <%= message.created_at %> </br>
            Message: <%= message.messageText %> </br></br>
          <% end %>
          
          <h4> Make appointment:</h1>
          <% Appointment.all.each do |appointment| %>
            Appointment ID: <%= appointment.id %> </br>
            Patient name: <%= appointment.appointmentPatientName %> </br>
            Time: <%= appointment.created_at %> </br>
            Appointment Notes: <%= appointment.appointmentNotes %> </br> </br>
          <% end %>
      </div>
      </div>
    </div>
      <!-- form end  -->
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Group Project</title>

    <%= render 'layouts/shim' %>
    

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= render 'layouts/shim' %>
    
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    
  </body>
</html>